package com.example.hospital.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
public class Appointment {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "appointment_seq")
    @SequenceGenerator(name = "appointment_seq", sequenceName = "appointment_seq", allocationSize = 1)
    private Long id;  // ID will be auto-generated by the sequence

    @Column(length = 100, nullable = false)
    private String patientName;

    @Column(length = 100, nullable = false)
    private String email;

    @Column(length = 15, nullable = false)
    private String phone;

    @Column(length = 100, nullable = false)
    private String doctor;

    @Column(nullable = false)
    private LocalDateTime appointmentTime;

    // No-argument constructor for JPA
    public Appointment() {
    }

    // Parameterized constructor for easy object creation
    public Appointment(String patientName, String email, String phone, String doctor, LocalDateTime appointmentTime) {
        this.patientName = patientName;
        this.email = email;
        this.phone = phone;
        this.doctor = doctor;
        this.appointmentTime = appointmentTime;
    }

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPatientName() {
        return patientName;
    }

    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getDoctor() {
        return doctor;
    }

    public void setDoctor(String doctor) {
        this.doctor = doctor;
    }

    public LocalDateTime getAppointmentTime() {
        return appointmentTime;
    }

    public void setAppointmentTime(LocalDateTime appointmentTime) {
        this.appointmentTime = appointmentTime;
    }

    @Override
    public String toString() {
        return "Appointment{" +
                "id=" + id +
                ", patientName='" + patientName + '\'' +
                ", email='" + email + '\'' +
                ", phone='" + phone + '\'' +
                ", doctor='" + doctor + '\'' +
                ", appointmentTime=" + appointmentTime +
                '}';
    }
}
